export enum STATUS {
  ACTIVE = 1,
  INACTIVE = 2,
  DELETE = 3,
}

export enum LOCAL_STORAGE_KEY {
  USER = 'USER',
  SETTING = 'SETTING',
  ALL_DATA = 'ALL_DATA',
  PRODUCT_WILDCARD = 'PRODUCT_WILDCARD',
  BRAND_WILDCARD = 'BRAND_WILDCARD',
  GROUP_WILDCARD = 'GROUP_WILDCARD',
}
