export enum Route {
  LOGIN = 'LOGIN',
  MAIN = 'MAIN',
  STORE = 'STORE',
  PRODUCT = 'PRODUCT',
  PRODUCT_LIST = 'PRODUCT_LIST',
  PRODUCT_UPDATE = 'PRODUCT_UPDATE',
  POS_SELLER = 'POS_SELLER',
  BRANCH = 'BRANCH',
  GROUP = 'GROUP',
  OPERATION_DETAIL = 'OPERATION_DETAIL',
}
